/*
 * Created on 24 Mar 2018 ( Time 12:24:10 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.trung.smallshop.domain.dto;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.math.BigDecimal;

public class ProductDto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 50 )
    private String productName;

    @NotNull
    private Integer supplierId;


    private BigDecimal unitPrice;

    @Size( max = 30 )
    private String productPackage;

    @NotNull
    private Boolean isDiscontinued;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setProductName( String productName ) {
        this.productName = productName;
    }
    public String getProductName() {
        return this.productName;
    }

    public void setSupplierId( Integer supplierId ) {
        this.supplierId = supplierId;
    }
    public Integer getSupplierId() {
        return this.supplierId;
    }

    public void setUnitPrice( BigDecimal unitPrice ) {
        this.unitPrice = unitPrice;
    }
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }

    public void setProductPackage( String productPackage ) {
        this.productPackage = productPackage;
    }
    public String getProductPackage() {
        return this.productPackage;
    }

    public Boolean getDiscontinued() {
        return isDiscontinued;
    }

    public void setDiscontinued(Boolean discontinued) {
        isDiscontinued = discontinued;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(productName);
        sb.append("|");
        sb.append(supplierId);
        sb.append("|");
        sb.append(unitPrice);
        sb.append("|");
        sb.append(productPackage);
        sb.append("|");
        sb.append(isDiscontinued);
        return sb.toString(); 
    } 


}
