/*
 * Created on 24 Mar 2018 ( Time 12:23:31 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.trung.smallshop.service.mapping;

import com.trung.smallshop.domain.dto.CustomerDto;
import com.trung.smallshop.domain.entity.Customer;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class CustomerServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public CustomerServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'Customer' to 'CustomerDto'
	 * @param customer
	 */
	public CustomerDto mapCustomerToCustomerDto(Customer customer) {
		if(customer == null) {
			return null;
		}

		//--- Generic mapping 
		CustomerDto customerDto = map(customer, CustomerDto.class);

		return customerDto;
	}
	
	/**
	 * Mapping from 'CustomerDto' to 'Customer'
	 * @param customerDto
	 * @param customer
	 */
	public void mapCustomerDtoToCustomer(CustomerDto customerDto, Customer customer) {
		if(customerDto == null) {
			return;
		}

		//--- Generic mapping 
		map(customerDto, customer);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}