/*
 * Created on 24 Mar 2018 ( Time 12:23:31 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.trung.smallshop.service.mapping;

import com.trung.smallshop.domain.dto.OrderDto;
import com.trung.smallshop.domain.entity.Customer;
import com.trung.smallshop.domain.entity.Order;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class OrderServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public OrderServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'Order' to 'OrderDto'
	 * @param order
	 */
	public OrderDto mapOrderToOrderDto(Order order) {
		if(order == null) {
			return null;
		}

		//--- Generic mapping 
		OrderDto orderDto = map(order, OrderDto.class);

		//--- Link mapping ( link to CustomerDto )
		if(order.getCustomer() != null) {
			orderDto.setCustomerId(order.getCustomer().getId());
		}
		return orderDto;
	}
	
	/**
	 * Mapping from 'OrderDto' to 'Order'
	 * @param orderDto
	 * @param order
	 */
	public void mapOrderDtoToOrder(OrderDto orderDto, Order order) {
		if(orderDto == null) {
			return;
		}

		//--- Generic mapping 
		map(orderDto, order);

		//--- Link mapping ( link : orderDto )
		if( hasLinkToCustomer(orderDto) ) {
			Customer customer1 = new Customer();
			customer1.setId( orderDto.getCustomerId() );
			order.setCustomer( customer1 );
		} else {
			order.setCustomer( null );
		}

	}
	
	/**
	 * Verify that CustomerDto id is valid.
	 * @param orderDto OrderDto
	 * @return boolean
	 */
	private boolean hasLinkToCustomer(OrderDto orderDto) {
		if(orderDto.getCustomerId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}