/*
 * Created on 24 Mar 2018 ( Time 12:23:31 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.trung.smallshop.service.mapping;

import com.trung.smallshop.domain.dto.ProductDto;
import com.trung.smallshop.domain.entity.Product;
import com.trung.smallshop.domain.entity.Supplier;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class ProductServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public ProductServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'Product' to 'ProductDto'
	 * @param product
	 */
	public ProductDto mapProductToProductDto(Product product) {
		if(product == null) {
			return null;
		}

		//--- Generic mapping 
		ProductDto productDto = map(product, ProductDto.class);

		//--- Link mapping ( link to SupplierDto )
		if(product.getSupplier() != null) {
			productDto.setSupplierId(product.getSupplier().getId());
		}
		return productDto;
	}
	
	/**
	 * Mapping from 'ProductDto' to 'Product'
	 * @param productDto
	 * @param product
	 */
	public void mapProductDtoToProduct(ProductDto productDto, Product product) {
		if(productDto == null) {
			return;
		}

		//--- Generic mapping 
		map(productDto, product);

		//--- Link mapping ( link : product )
		if( hasLinkToSupplier(productDto) ) {
			Supplier supplier1 = new Supplier();
			supplier1.setId( productDto.getSupplierId() );
			product.setSupplier( supplier1 );
		} else {
			product.setSupplier( null );
		}

	}
	
	/**
	 * Verify that SupplierDto id is valid.
	 * @param productDto ProductDto
	 * @return boolean
	 */
	private boolean hasLinkToSupplier(ProductDto productDto) {
		if(productDto.getSupplierId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}