/*
 * Created on 24 Mar 2018 ( Time 12:24:10 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.trung.smallshop.service;

import com.trung.smallshop.domain.dto.CustomerDto;

import java.util.List;

/**
 * Business Service Interface for entity CustomerDto.
 */
public interface CustomerService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	CustomerDto findById(Integer id) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<CustomerDto> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	CustomerDto save(CustomerDto entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	CustomerDto update(CustomerDto entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	CustomerDto create(CustomerDto entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete(Integer id);


}
