/*
 * Created on 24 Mar 2018 ( Time 12:24:10 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.trung.smallshop.service;

import com.trung.smallshop.domain.dto.OrderDto;

import java.util.List;

/**
 * Business Service Interface for entity OrderDto.
 */
public interface OrderService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	OrderDto findById(Integer id) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<OrderDto> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	OrderDto save(OrderDto entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	OrderDto update(OrderDto entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	OrderDto create(OrderDto entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete(Integer id);


}
