/*
 * Created on 24 Mar 2018 ( Time 12:24:11 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.trung.smallshop.service;

import com.trung.smallshop.domain.dto.ProductDto;

import java.util.List;

/**
 * Business Service Interface for entity ProductDto.
 */
public interface ProductService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	ProductDto findById(Integer id) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<ProductDto> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	ProductDto save(ProductDto entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	ProductDto update(ProductDto entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	ProductDto create(ProductDto entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete(Integer id);


}
