/*
 * Created on 24 Mar 2018 ( Time 12:24:11 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.trung.smallshop.service;

import com.trung.smallshop.domain.dto.SupplierDto;

import java.util.List;

/**
 * Business Service Interface for entity SupplierDto.
 */
public interface SupplierService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	SupplierDto findById(Integer id) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<SupplierDto> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	SupplierDto save(SupplierDto entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	SupplierDto update(SupplierDto entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	SupplierDto create(SupplierDto entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete(Integer id);


}
