/*
 * Created on 24 Mar 2018 ( Time 12:24:10 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.trung.smallshop.rest.controller;

import com.trung.smallshop.domain.dto.CustomerDto;
import com.trung.smallshop.service.CustomerService;
import org.springframework.cache.annotation.CacheConfig;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import javax.annotation.Resource;
import java.util.List;

/**
 * Spring MVC controller for 'Customer' management.
 */
@Controller
@CacheConfig(cacheNames = "weblevelCache")
public class CustomerRestController {

	@Resource
	private CustomerService customerService;


	@RequestMapping( value="/customers",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<CustomerDto> findAll() {
		return customerService.findAll();
	}

	@Cacheable
	@RequestMapping( value="/customers/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public CustomerDto findOne(@PathVariable("id") Integer id) {
		return customerService.findById(id);
	}

	@RequestMapping( value="/customers",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public CustomerDto create(@RequestBody CustomerDto customerDto) {
		return customerService.create(customerDto);
	}

	@RequestMapping( value="/customers/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public CustomerDto update(@PathVariable("id") Integer id, @RequestBody CustomerDto customerDto) {
		return customerService.update(customerDto);
	}

	@RequestMapping( value="/customers/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Integer id) {
		customerService.delete(id);
	}
	
}
