/*
 * Created on 24 Mar 2018 ( Time 12:24:10 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.trung.smallshop.rest.controller;

import com.trung.smallshop.domain.dto.OrderDto;
import com.trung.smallshop.service.OrderService;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import javax.annotation.Resource;
import java.util.List;

/**
 * Spring MVC controller for 'Order' management.
 */
@Controller
public class OrderRestController {

	@Resource
	private OrderService orderService;

	
	@RequestMapping( value="/orders",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<OrderDto> findAll() {
		return orderService.findAll();
	}

	@RequestMapping( value="/orders/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public OrderDto findOne(@PathVariable("id") Integer id) {
		return orderService.findById(id);
	}
	
	@RequestMapping( value="/order",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public OrderDto create(@RequestBody OrderDto orderDto) {
		return orderService.create(orderDto);
	}

	@RequestMapping( value="/orders/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public OrderDto update(@PathVariable("id") Integer id, @RequestBody OrderDto orderDto) {
		return orderService.update(orderDto);
	}

	@RequestMapping( value="/orders/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Integer id) {
		orderService.delete(id);
	}
	
}
