/*
 * Created on 24 Mar 2018 ( Time 12:24:11 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.trung.smallshop.rest.controller;

import com.trung.smallshop.domain.dto.ProductDto;
import com.trung.smallshop.service.ProductService;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import javax.annotation.Resource;
import java.util.List;

/**
 * Spring MVC controller for 'Product' management.
 */
@Controller
public class ProductRestController {

	@Resource
	private ProductService productService;

	
	@RequestMapping( value="/products",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<ProductDto> findAll() {
		return productService.findAll();
	}

	@RequestMapping( value="/products/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ProductDto findOne(@PathVariable("id") Integer id) {
		return productService.findById(id);
	}
	
	@RequestMapping( value="/products",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ProductDto create(@RequestBody ProductDto productDto) {
		return productService.create(productDto);
	}

	@RequestMapping( value="/products/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ProductDto update(@PathVariable("id") Integer id, @RequestBody ProductDto productDto) {
		return productService.update(productDto);
	}

	@RequestMapping( value="/products/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Integer id) {
		productService.delete(id);
	}
	
}
