/*
 * Created on 24 Mar 2018 ( Time 12:24:11 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.trung.smallshop.rest.controller;

import com.trung.smallshop.domain.dto.SupplierDto;
import com.trung.smallshop.service.SupplierService;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import javax.annotation.Resource;
import java.util.List;

/**
 * Spring MVC controller for 'Supplier' management.
 */
@Controller
public class SupplierRestController {

	@Resource
	private SupplierService supplierService;
	
	@RequestMapping( value="/suppliers",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<SupplierDto> findAll() {
		return supplierService.findAll();
	}

	@RequestMapping( value="/suppliers/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public SupplierDto findOne(@PathVariable("id") Integer id) {
		return supplierService.findById(id);
	}
	
	@RequestMapping( value="/suppliers",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public SupplierDto create(@RequestBody SupplierDto supplierDto) {
		return supplierService.create(supplierDto);
	}

	@RequestMapping( value="/suppliers/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public SupplierDto update(@PathVariable("id") Integer id, @RequestBody SupplierDto supplierDto) {
		return supplierService.update(supplierDto);
	}

	@RequestMapping( value="/suppliers/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Integer id) {
		supplierService.delete(id);
	}
	
}
